language: python
cache: pip
matrix:
  include:
  - python: 3.7
    dist: bionic
    sudo: true
branches:
  only:
    - master
notifications:
  recipients:
    - kapitan-admins@googlegroups.com
  email:
    on_success: change
    on_failure: always

before_install:
  # Loop until update succeeds (timeouts can occur)
  - sudo sed -e '/postgresql/ s/^#*/#/' -i /etc/apt/sources.list.d/*
  - sudo add-apt-repository ppa:longsleep/golang-backports -y
  # workaround for https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  # Loop until update succeeds (timeouts can occur)
  - travis_retry $(! sudo apt-get -qq update 2>&1 | grep Failed)
  - sudo apt-get install -y gnupg2 git

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage black kapitan==0.28.0-rc.1

script:
  - make test && make test_coverage
