---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesoro-admission-controller
  labels:
    app: tesoro-admission-controller
spec:
  selector:
    matchLabels:
      app: tesoro-admission-controller
  template:
    metadata:
      labels:
        app: tesoro-admission-controller
    spec:
      containers:
        - name: tesoro
          image: ramaro/tesoro
          ports:
            - containerPort: 8443
              name: tesoro-api
            - containerPort: 9095
              name: metrics
          args:
            - --port=8443
            - --cert-file=/certs/cert.pem
            - --key-file=/certs/priv.key


