---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tesoro-admission-controller
webhooks:
  - name: tesoro-admission-controller.tesoro.svc
    clientConfig:
      service:
        name: tesoro-admission-controller
        namespace: tesoro
        path: "/mutate"
      caBundle: ${CA_PEM_B64}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        resources:
          - "*"
        apiVersions:
          - "*"
