apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - secrets
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
