---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tesoro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tesoro.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 443
              name: tesoro-api
            - containerPort: 9095
              name: metrics
          args:
            - --port=443
            - --cert-file=/certs/cert.pem
            - --key-file=/certs/priv.key
          env:
          {{- range $index, $value := .Values.env }}
            - name: {{ $index }}
              value: {{ $value | quote }}
          {{- end }}
          envFrom:
          {{- range .Values.secrets }}
            - secretRef:
                name: {{.}}
                optional: false
          {{- end }}
          {{- with .Values.probes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tesoro-secrets
              mountPath: /certs
              readOnly: true
      volumes:
        - name: tesoro-secrets
          secret:
            secretName: {{ include "tesoro.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
