{{ $ca := genCA "tesoro-admission-controller-ca" 3650 }}
{{ $cn := printf "tesoro-admission-controller.%s.svc" .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tesoro.fullname" . }}.tesoro.svc
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        tesoro.kapicorp.com: enabled
    clientConfig:
      service:
        name: {{ include "tesoro.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        resources:
          - "*"
        apiVersions:
          - "*"
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "apps"
        resources:
          - "deployments"
        apiVersions:
          - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ b64enc $server.Cert }}
  priv.key: {{ b64enc $server.Key }}
