apiVersion: v1
kind: Service
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
spec:
  ports:
    - name: tesoro-api
      port: 443
      targetPort: tesoro-api
    - name: metrics
      port: 9095
      targetPort: metrics
  selector:
    {{- include "tesoro.selectorLabels" . | nindent 4 }}
