apiVersion: v1
kind: Service
metadata:
  name: {{ include "tesoro.fullname" . }}
  labels:
    {{- include "tesoro.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: tesoro-api
  selector:
    {{- include "tesoro.selectorLabels" . | nindent 4 }}
