apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  labels:
    tesoro.kapicorp.com: enabled
type: Opaque
stringData:
  cert.pem: "?{base64:eyJkYXRhIjogImNtVm1JREVnWkdGMFlRPT0iLCAiZW5jb2RpbmciOiAib3JpZ2luYWwiLCAidHlwZSI6ICJiYXNlNjQifQ==:embedded}"
